name: app_template
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: 3.7.12

dependencies:
  flutter:
    sdk: flutter
  async: 2.10.0
  equatable: 2.0.5
  flutter_formx: 2.0.1
  flutter_mobx: 2.0.6+5
  get_it: 7.6.0
  injectable: 2.1.2
  mobx: 2.1.3+1
  mobx_codegen: 2.1.1
  page_view_dot_indicator: 2.1.0
  sliver_tools: 0.2.10
  awesome_dio_interceptor: 1.0.0
  dio: 5.2.0
  flutter_secure_storage: 8.0.0
  http: 0.13.6
  http_parser: 4.0.2
  json_annotation: 4.8.1
  retrofit: 4.0.1
  flutter_native_timezone: ^2.0.0
  package_info_plus: ^4.0.2
  flutter_fimber: ^0.7.1
  fimber: ^0.7.0
  firebase_crashlytics: ^3.3.4
  firebase_core: ^2.15.0
  firebase_remote_config: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  build_runner: 2.3.3
  fake_async: 1.3.1
  injectable_generator: 2.1.6
  json_serializable: 6.6.2
  mockito: 5.4.0
  retrofit_generator: 7.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
